---
# install rust

- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  become: false

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
  become: false

- name: Add cargo to bash PATH
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.bashrc
    regexp: '^export PATH=.*'
    line: 'export PATH="$PATH:$HOME/.cargo/bin"'
    insertafter: EOF
  tags:
    - rust
  become: false

- name: Add cargo to zsh PATH
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    regexp: '^export PATH=.*'
    line: 'export PATH="$PATH:$HOME/.cargo/bin"'
    insertafter: EOF
  tags:
    - rust
  become: false
