---
- hosts: all
  become: true
  tasks:
    - name: echo whoami
      shell: whoami
      register: whoami_result
      become: no
    - name: Show whoami
      debug:
        var: whoami_result.stdout
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    
