---
  
- block: 
    - name: Check OS
      set_fact:
        is_ubuntu: "{{ ansible_os_family == 'Debian' }}"
        is_mac: "{{ ansible_os_family == 'Darwin' }}"

    - name: Echo whoami
      shell: whoami
      register: whoami_result
      become: false

    - name: Show whoami
      debug:
        var: whoami_result.stdout

    - name: Install Zsh (Ubuntu)
      become: true
      ansible.builtin.apt:
        name: "{{ ['zsh'] }}"
        state: present
        update_cache: yes
      when: is_ubuntu

    - name: Install Zsh (macOS)
      homebrew:
        name: zsh
        state: present
        update: yes
      when: is_mac

    # - name: Ensure zsh is the default shell
    #   user:
    #     name: "{{ ansible_user }}"
    #     shell: "/usr/bin/zsh"
    #   become: true

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
