---
  
- block: 
    - name: Check OS
      set_fact:
        is_ubuntu: "{{ ansible_os_family == 'Debian' }}"
        is_mac: "{{ ansible_os_family == 'Darwin' }}"

    - name: Echo whoami
      shell: whoami
      register: whoami_result
      become: false

    - name: Show whoami
      debug:
        var: whoami_result.stdout

    - name: Install Zsh (Ubuntu)
      become: true
      ansible.builtin.apt:
        name: "{{ ['zsh'] }}"
        state: present
        update_cache: yes
      when: is_ubuntu

    - name: Install Zsh (macOS)
      homebrew:
        name: zsh
        state: present
        update: yes
      when: is_mac

    - name: Set user shell to zsh
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      become: true

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{ user }}/install.sh"
        mode: '0755'

    - name: Install ohmyzsh
      ansible.builtin.script:
        cmd: "/home/{{ user }}/install.sh"

    - name: Download NerdFonts
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
        dest: "/home/{{ user }}/Meslo.zip"

    - name: Create temp directory
      ansible.builtin.file:
        path: "/home/{{ user }}/Meslo"
        state: directory
        mode: '0755'

    - name: Install font files
      ansible.builtin.unarchive:
        src: "/home/{{ user }}/Meslo.zip"
        dest: "/home/{{ user }}/Meslo"

    - name: Move font files to fonts directory
      ansible.builtin.copy:
        src: "/home/{{ user }}/Meslo"
        dest: /usr/share/fonts/Meslo
        owner: root
      become: true