---
# install Github CLI

## excute install.sh

- name: Install gh
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: 0755

- name: Run install.sh
  shell: /tmp/install.sh
  become: true
  args:
    chdir: /tmp
  tags:
    - gh