---

# Download starship
- name: Download starship
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  become: false

# install starship

- name: Run install.sh
  shell: /tmp/starship_install.sh --yes
  become: true
  args:
    executable: /bin/bash

# source starship
- name: Source starship
  lineinfile:
    path: /home/{{ user }}/.bashrc
    line: |
      eval "$(starship init bash)"
  become: false