---
  - name: Download docker install bash
    get_url: 
      url: https://get.docker.com
      dest: /tmp/docker-installer.sh
  - name: Execute the docker-installer.sh
    shell: sh /tmp/docker-installer.sh
  - name: Add user to docker group
    shell: usermod -aG docker {{ user }}
  - name: Remove file
    file: 
      path: /tmp/docker-installer.sh
      state: absent