---
# install neovim

# curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
# sudo rm -rf /opt/nvim
# sudo tar -C /opt -xzf nvim-linux64.tar.gz

- name: Downlaod neovim
  get_url: 
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
    mode: '0755'


- name: Remove existing Neovim installation
  ansible.builtin.command: rm -rf /opt/nvim
  become: false

- name: Install neovim
  become: true 
  ansible.builtin.command: tar -C /opt -xzf /tmp/nvim-linux64.tar.gz

- name: Backup existing Neovim configuration
  command: mv /home/{{ user }}/.config/nvim /home/{{ user }}/.config/nvim.bak
  args:
    removes: /home/{{ user }}/.config/nvim.bak
  ignore_errors: true
  become: false

- name: Clone LazyVim repository
  git:
    repo: https://github.com/LazyVim/starter.git
    dest: /home/{{ user }}/.config/nvim
  become: false

- name: Change ownership of nvim configuration directory
  ansible.builtin.file:
    path: /home/{{ user }}/.config/nvim
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true
